### PR TITLE
fix small typo

### PR DESCRIPTION
**Pull request by HDembinski**

### CODE REVIEW

**Comment by HDembinski** [comment]
@afedynitch @jncots Perhaps you could unprotect the master branch so that small typo fixes like this can be merged by the author? I found a few other typos that I introduced in the readme and I don't want to make PRs for stuff like that.

**Comment by HDembinski** [comment]
Or keep the protection, but do not enforce a review. In small teams where everyone knows everyone, it is not necessary to enforce such rigid structures. The git history makes everything undoable and the social consequences for going rogue and making changes that the others do not agree with would be swift.

**Comment by jncots** [comment]
I wonder is it possible to have different settings for each contributor? I would leave the block for merging for myself, as it saved me once from  inadvertent merge. Aside from that I fine with not enforcing a review for every PR.

**Comment by afedynitch** [comment]
As a compromise, I have added Hans to the list of people who can bypass these protections. I'm fine with small typos not going though reviews. But I'd like to see and actively take note of the changes flowing into the code. Since this is one of 8 or 9 (non-software) projects I'm working on simultaneously, I appreciate to get notified and see summaries if something happens.

**Review by afedynitch — APPROVED** [review]

**Comment by HDembinski** [comment]
Great, thanks! I will not misuse this power and I am also ok with going back to a more rigid structure if that will become necessary.

**Pull request merged**
