### PR TITLE
Add rng_state

### PR DESCRIPTION
**Pull request by jncots**
As it was discussed there is a need for control of random number generator for testing and debug purposes. The required for this basic functions are: view and copy a current state of generator and restore the state from the saved copy. 

The working example/prototype (currently only for Sophia) is following

```python
import impy
from impy.kinematics import FixedTarget
from impy.constants import TeV, GeV
import numpy as np

ekin = FixedTarget(13 * TeV, "photon", "proton")
generator = impy.models.Sophia20(ekin)

# One can get a view (currently it is copy and it will converted to view):
state0 = generator.rng_state
print("Before run = ", state0.counter, state0.seed)
# Or the same
print("Before run = ", generator.rng_state.counter, generator.rng_state.seed)

# Save a state to a variable:
state0 = state0.copy()

counters = []

for event in generator(10):
    # Print the value of counter (how many time the 
    # random number generator has been called so far) after each event
    print("rng calls = ", generator.rng_state.counter)
    counters.append(generator.rng_state.counter)


# One can save the state to file
generator.dump_rng_state_to("rng_state.dat")
# Or to variable
state1 = generator.rng_state.copy()

# Restore the state from variable
generator.rng_state = state0

# And compare to check whether the state is restored: 
i = 0
for event in generator(10):
    assert counters[i] == generator.rng_state.counter, "Not equal"
    i  = i + 1

state2 = generator.rng_state.copy()
# Restore from file
generator.restore_rng_state_from("rng_state.dat")

# And check for equality
if state2 == generator.rng_state:
    print("Equal")
```

I am not really happy with descriptive but still long names for `restore_rng_state_from` and `dump_rng_state_to`. It would be good to find something more concise.

### CODE REVIEW

**Comment by afedynitch** [comment]
@HDembinski in case you're wondering what this is about. We will update the description, purpose and proposed implementation of the PR after a discussion we had here...

**Comment by HDembinski** [comment]
Instead of custom serialization routines, please support Pythons serialization infrstructure by implementing `__getstate__` and `__setstate__`. You get many benefits for free, like saving in different formats or transparent compression.

**Comment by jncots** [comment]
The above is a commit with working access to random number generator state for Sophia, Pythia6 and EPOS-LHC. `CMakeLists.txt` will be cleaned in the next commits. Here I just fixed the working state. 

`CMakeLists.txt` should have a function for preprocessing original files, because the pattern 

```cmake
set(pythia6_pythia6428_source pythia-6.4.28.f)
add_custom_command(
  OUTPUT ${pythia6_pythia6428_source}
  COMMAND ${CMAKE_Fortran_COMPILER}
    -E -cpp ${fortran_dir}/pythia6/pythia-6.4.28.f
    -o ${pythia6_pythia6428_source}
    -DIMPY
)
```

is met to often. It is needed to remove/substitute functions in original source files. 

Also, it would be convenient to have  function that copy newly generated *.pyf files to `f2py_dir`

**Comment by afedynitch** [comment]
> The above is a commit with working access to random number generator state for Sophia, Pythia6 and EPOS-LHC. `CMakeLists.txt` will be cleaned in the next commits. Here I just fixed the working state.
> 
> `CMakeLists.txt` should have a function for preprocessing original files, because the pattern
> 
> ```cmake
> set(pythia6_pythia6428_source pythia-6.4.28.f)
> add_custom_command(
>   OUTPUT ${pythia6_pythia6428_source}
>   COMMAND ${CMAKE_Fortran_COMPILER}
>     -E -cpp ${fortran_dir}/pythia6/pythia-6.4.28.f
>     -o ${pythia6_pythia6428_source}
>     -DIMPY
> )
> ```
> 
> is met to often. It is needed to remove/substitute functions in original source files.
> 
> Also, it would be convenient to have function that copy newly generated *.pyf files to `f2py_dir`

If you just want to pass a preprocessor flag to the compiler, you can do:
```
target_compile_definitions(target__name PRIVATE IMPY)
target_compile_options(target__name PRIVATE -cpp)
```

**Comment by HDembinski** [comment]
> is met to often. It is needed to remove/substitute functions in original source files.

I can write a function to encapsulate this or you follow Anatoli's advice.
```
target_compile_options(target__name PRIVATE -cpp)
```
This will work for compiling into a library with `add_library`, but it won't work when you need to run numpy.f2py. The function `f2py_add_library` does not run the preprocessor on the sources automatically, because it does not know that numpy.f2py depends on preprocessed sources. So even if you add `-cpp` to all files, numpy.f2py will see the unmodified sources and probably choke on them.

**Comment by HDembinski** [comment]
> Also, it would be convenient to have function that copy newly generated *.pyf files to `f2py_dir`

Do you mean in cmake or as a shell script? The shell script would be a one-liner. We do not want to copy those files automatically in cmake, I think. As a principle, cmake should not modify the source files, only files in its build area that is seprate from the source.

**Comment by jncots** [comment]
I am closing this draft PR because it was merged to PR #59 and later development has been done there.

**Pull request closed without merging**
